FROM alpine AS builder
EXPOSE 3000
WORKDIR /app
RUN apk add --update npm
COPY . .
CMD npm ci && npm run build

FROM nginx:alpine AS runner
EXPOSE 80
COPY --from=builder /app/build /usr/share/nginx/html
CMD ["nginx","-g","daemon off;"]